development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rcloud_development
  pool: 5
  username: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rcloud_test
  pool: 5
  username: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: rcloud_development
  pool: 5
  username: root
  host: localhost